#!/usr/bin/env bash
BIN_LOCATION="${HOME}/.local/bin"
CCLI_SERVE_PATH="${BIN_LOCATION}/ccli"
CCLI_INSTALL_LOCATION="${HOME}/.local/share/container-cli"
CCLI_INSTALL_LOCATION_ROOT=$(dirname "${CCLI_INSTALL_LOCATION}")
CCLI_CONFIG_PATH="${HOME}/.config/container-cli/.config.sh"
CCLI_CONFIGURATOR_PATH="${CCLI_INSTALL_LOCATION}/config.sh"
CCLI_REPO="git@gitlab.com:locke-codes/container-cli.git"

CONFIG_PATH=${1-${CCLI_CONFIG_PATH}}
INSTALL_LOCATION=${2-${CCLI_INSTALL_LOCATION}}
ENGINE=${3-docker}
COMPOSE_ENGINE=${4-docker-compose}
REPOSITORY=$5
COMMAND_PREFIX=$6

INSTALL_LOCATION_ROOT=$(dirname "${INSTALL_LOCATION}")

echo "Creating configuration file"
cat << EOF > "${CONFIG_PATH}"
#!/usr/bin/env bash
ENGINE=${ENGINE}
COMPOSE=${COMPOSE_ENGINE}
BIN_LOCATION=${BIN_LOCATION}
CCLI_INSTALL_LOCATION=${CCLI_INSTALL_LOCATION}
CCLI_INSTALL_LOCATION_ROOT=${CCLI_INSTALL_LOCATION_ROOT}
INSTALL_LOCATION=${INSTALL_LOCATION}
INSTALL_LOCATION_ROOT=${INSTALL_LOCATION_ROOT}
CONFIG_PATH=${CONFIG_PATH}
CCLI_CONFIGURATOR_PATH=${CCLI_CONFIGURATOR_PATH}
CCLI_REPO=${CCLI_REPO}
CCLI_SERVE_PATH=${CCLI_SERVE_PATH}
REPOSITORY=${REPOSITORY}
COMMAND_PREFIX=${COMMAND_PREFIX}
export ENGINE COMPOSE BIN_LOCATION CCLI_INSTALL_LOCATION CCLI_INSTALL_LOCATION_ROOT \
  INSTALL_LOCATION INSTALL_LOCATION_ROOT CONFIG_PATH CCLI_CONFIGURATOR_PATH CCLI_REPO \
  CCLI_SERVE_PATH REPOSITORY COMMAND_PREFIX
EOF

chmod +x "${CONFIG_PATH}"

echo "Configuration file: ${CONFIG_PATH}.
Edit this file to change docker and compose engines"